// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Task Tracker",
  description: "A simple task management app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav
          style={{
            background: "white",
            borderBottom: "1px solid #e5e7eb",
            padding: "0 2rem",
            height: "56px",
            display: "flex",
            alignItems: "center",
            gap: "2rem",
          }}
        >
          <span style={{ fontWeight: 600, fontSize: "1rem" }}>
            Task Tracker
          </span>
          <a
            href="/"
            style={{
              color: "#374151",
              textDecoration: "none",
              fontSize: "0.875rem",
            }}
          >
            Home
          </a>
          <a
            href="/dashboard"
            style={{
              color: "#374151",
              textDecoration: "none",
              fontSize: "0.875rem",
            }}
          >
            Dashboard
          </a>
          <a
            href="/login"
            style={{
              color: "#374151",
              textDecoration: "none",
              fontSize: "0.875rem",
            }}
          >
            Login
          </a>
        </nav>
        {children}
      </body>
    </html>
  );
}
